name: vgib
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - tqdm
  - h5py
  - seaborn
  - pytest
  - pip
  - pip:
      - ruff>=0.5
      - build>=1.2
      - twine>=5.0
